### ISSUE TITLE
Cannot read property 'model' of undefined

### ISSUE THREAD

**Issue by franciscop** [whitecolor/mongoose-fill#9]
I have an array of favorites and wanted to set a virtual field "followers" in this way:

```js
userSchema.fill('followers', function(callback){
  var somefavs = { "favorites.innerArray.0": { $exists: true } };
  this.db.model('User').find(somefavs, function (err, favs) {
    callback(null, parseInt(Math.random() * 100));
  });
});
```

However, it throws the following error:

```
1) controllers/favorite.js favorite.ids() can aggregate followers:
     Uncaught TypeError: Cannot read property 'model' of undefined
      at Object.<anonymous> (models/users.js:9:1733)
      at fillDoc (node_modules/mongoose-fill/index.js:60:23)
      at node_modules/mongoose-fill/index.js:297:17
      at node_modules/mongoose-fill/node_modules/async/lib/async.js:356:13
      at async.forEachOf.async.eachOf (node_modules/mongoose-fill/node_modules/async/lib/async.js:233:13)
      at _asyncMap (node_modules/mongoose-fill/node_modules/async/lib/async.js:355:9)
      at Object.map (node_modules/mongoose-fill/node_modules/async/lib/async.js:337:20)
      at node_modules/mongoose-fill/index.js:296:21
      at node_modules/mongoose-fill/node_modules/async/lib/async.js:356:13
      at async.forEachOf.async.eachOf (node_modules/mongoose-fill/node_modules/async/lib/async.js:233:13)
      at _asyncMap (node_modules/mongoose-fill/node_modules/async/lib/async.js:355:9)
      at Object.map (node_modules/mongoose-fill/node_modules/async/lib/async.js:337:20)
      at node_modules/mongoose-fill/index.js:202:15
      at node_modules/mongoose-fill/node_modules/async/lib/async.js:356:13
      at iterate (node_modules/mongoose-fill/node_modules/async/lib/async.js:262:13)
      at async.forEachOfSeries.async.eachOfSeries (node_modules/mongoose-fill/node_modules/async/lib/async.js:281:9)
      at _asyncMap (node_modules/mongoose-fill/node_modules/async/lib/async.js:355:9)
      at Object.mapSeries (node_modules/mongoose-fill/node_modules/async/lib/async.js:347:20)
      at node_modules/mongoose-fill/index.js:200:13
      at Query.<anonymous> (node_modules/mongoose/lib/query.js:2181:28)
      at node_modules/kareem/index.js:259:21
      at node_modules/kareem/index.js:127:16
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

If I remove the single part calling the `this.db.model()` it works flawlessly:

```js
userSchema.fill('followers', function(callback){
  callback(null, parseInt(Math.random() * 100));
});
```

I have no idea why this happens as it looks almost the same as the documentation. One thing to note is that the model to retrieve is the same as the schema we are working with (User). However, since the problem is that it cannot find the function `.model()` and not that it cannot find the model itself, I think it might be an error with `mongoose-fill` itself.

**Comment by whitecolor** [comment]
Quite strange, tests seem to pass with `this.db` checked inside. 
What mongoose version do you use?
And can you check what is `this` inside your fill callback?

**Comment by franciscop** [comment]
`this` seems to be an instance of my schema. With this `console.log()`:

```js
userSchema.fill('followers', function(callback){
  console.log("This: ", this, this.db);
  callback(null, parseInt(Math.random() * 100));
});
```

I get this result (added enter for clarity and some things replaced by XXX). All data is randomly made up for tests:

```js
This:

{ _id: 577d60692bd4d9770c60777d,
  fullname: 'Elnora Hammond',
  email: 'mafil@gocfa.hn',
  password: '$2a$10$PZN/TPaq8z4mpcQOvKGHzeQ/UBhEbDRjnBXR5qCbD6dgHxoxJvQ1K',
  gender: 'other',
  imei: 'xK0!rUvo@AoO!WzoHEkP',
  google_email: 'wesedfuv@urife.my',
  facebook_id: '1000054640020151',
  __v: 0,
  stream_token: '',
  capacity: 0,
  min_age: 0,
  recommended: false,
  added: 2016-07-06T19:47:53.539Z,
  modified: 2016-07-06T19:47:53.539Z,
  genres: [],
  favorites: [],
  token: 'bf4f0f3721515d8e4541004855f31872e65817b0cf1a3e39c18abc6ab9fad179f882ce40aabcc69e1a3dd18915faaf26ea427cb1d9f33eda7a329df81845687c',
  role: 'local',
  followers: undefined,
  contact: undefined,
  id: '577d60692bd4d9770c60777d' }

NativeConnection {
  base: 
   Mongoose {
     connections: [ [Circular] ],
     plugins: [],
     models: { User: [Object] },
     modelSchemas: { User: [Object] },
     options: { pluralization: true } },
  collections: 
   { users: 
      NativeCollection {
        collection: [Object],
        opts: [Object],
        name: 'users',
        collectionName: 'users',
        conn: [Circular],
        queue: [],
        buffer: false,
        emitter: [Object] } },
  models: 
   { User: 
      { [Function: model]
        hooks: [Object],
        base: [Object],
        modelName: 'User',
        model: [Function: model],
        db: [Circular],
        discriminators: undefined,
        __fill: [Object],
        create: [Function],
        login: [Function],
        register: [Function],
        set: [Function],
        schema: [Object],
        collection: [Object],
        Query: [Object],
        '$__insertMany': [Function],
        insertMany: [Function] } },
  config: { autoIndex: true },
  replica: false,
  hosts: null,
  host: '127.0.0.1',
  port: 27017,
  user: undefined,
  pass: undefined,
  name: 'XXX',
  options: 
   { db: 
      { forceServerObjectId: false,
        w: 1,
        promiseLibrary: [Function: Promise] },
     auth: {},
     server: { socketOptions: {}, auto_reconnect: true },
     replset: { socketOptions: {} },
     mongos: undefined },
  otherDbs: [],
  _readyState: 1,
  _closeCalled: false,
  _hasOpened: true,
  _listening: false,
  _events: { error: [Function: bound bound ] },
  _eventsCount: 1,
  db: 
   EventEmitter {
     domain: null,
     _events: 
      { close: [Function],
        error: [Function],
        reconnect: [Function],
        timeout: [Function],
        open: [Function],
        parseError: [Function] },
     _eventsCount: 6,
     _maxListeners: undefined,
     s: 
      { databaseName: 'litomo',
        dbCache: {},
        children: [],
        topology: [Object],
        options: [Object],
        logger: [Object],
        bson: {},
        authSource: undefined,
        readPreference: undefined,
        bufferMaxEntries: -1,
        parentDb: null,
        pkFactory: undefined,
        nativeParser: undefined,
        promiseLibrary: [Function: Promise],
        noListener: false,
        readConcern: undefined },
     serverConfig: [Getter],
     bufferMaxEntries: [Getter],
     databaseName: [Getter],
     _listening: true } }
```

**Comment by whitecolor** [comment]
`this.db.model` is undefined? what is your mongoose version?

**Comment by franciscop** [comment]
My mongoose version specified in the `package.json`, is the `^4.4.20` so the one installed is:

**`4.5.3`**

**Comment by whitecolor** [comment]
Well it is strange that model instance doesn't have `db` property. I recently tried `4.5.3` and all tests passed. that is really.

**Comment by franciscop** [comment]
Mongodb is version `v2.6.10`, what about that?

**Comment by whitecolor** [comment]
> http://mongoosejs.com/docs/compatibility.html

**Comment by franciscop** [comment]
FWIW, `this.model` is undefined, but `this.models` is defined as you can see in the log above:

```
  models: 
   { User: 
      { [Function: model]
        hooks: [Object],
        base: [Object],
        modelName: 'User',
        model: [Function: model],
        db: [Circular],
        discriminators: undefined,
        __fill: [Object],
        create: [Function],
        login: [Function],
        register: [Function],
        set: [Function],
        schema: [Object],
        collection: [Object],
        Query: [Object],
        '$__insertMany': [Function],
        insertMany: [Function] } },
```

I will try something with it

**Comment by franciscop** [comment]
@whitecolor it seems compatible:

```
MongoDB Server 2.6.x: mongoose ~3.8.8, 4.x
```

Using MongoDB 2.6.4 with mongoose 4.5.3

**Comment by whitecolor** [comment]
well **this** should be **model instance** not schema instance or something.
mongoDB version should be no problem.

**Comment by whitecolor** [comment]
reopen if needed
